### ISSUE TITLE
Why do you daisy chain the hotkeys?

### ISSUE THREAD

**Issue by mmikeww** [stevep99/keyboard-tweaks#2]
For example, you remap `RAlt::F20` and then do `F20 & Key::`

Why not just do `RAlt & Key::` directly?

**Comment by stevep99** [comment]
The reason for this is flexibility:  it allows people to use a different modifier key if they want to. 
For example, some may want to keep their RAlt as-is, and define a different key, e.g. CapsLock, as F20.

**Comment by mmikeww** [comment]
Gotcha, that makes sense. You could set a variable and use the Hotkey command, but there really is no harm in using F20 since that key is almost never used
