### ISSUE TITLE
Extend std layer script seems to be the wide script

### ISSUE THREAD

**Issue by martinfreedman** [stevep99/keyboard-tweaks#6]
Key mappings are all shifted to the right one key from what I expected the standard keyboard to be, as according to your key mappings png files and in read me description. This seems to be a wide file not standard UK Qwerty?

Great work by the way exactly what I was looking for.

**Comment by stevep99** [comment]
Are you using this file: https://github.com/stevep99/keyboard-tweaks/blob/master/ExtendLayer/extend_layer_std.ahk ?

**Comment by martinfreedman** [comment]
I had checked this file twice. Anyway just copy pasted this again and it now works correctly
