### ISSUE TITLE
Extend layer breaks middle click

### ISSUE THREAD

**Issue by ea-ae** [stevep99/keyboard-tweaks#8]
Leaving this issue here for anybody else who might run across similar issues with the extend AHK scripts on win10.

When running the extend AHK scripts, for some very peculiar reason it was no longer possible to perform middle-clicks. To fix this, simply remove this part:

```ahk
#InputLevel 1
CapsLock::F22
#InputLevel 0
```

Then replace all the instances of `F22` in the script with `CapsLock` using any text editor's find-and-replace feature.

**Comment by stevep99** [comment]
Do you know if this only happens when using F22 (rather than some other F key)?
Or is it the use of #InputLevel that's causing the problem?

**Comment by ea-ae** [comment]
Just checked, replacing `F22` with something like `F24` does indeed fix the issue.

**Comment by stevep99** [comment]
OK thanks, that sounds like a good solution. Have applied the fix.
